### ISSUE TITLE
Update Wetter_de_scraping.py

### ISSUE THREAD

**Issue by danvardan15** [BCCN-Prog/webscraping_2018#13]
Parse values for precipitation_l such that a float is always stored and not a string sucha as "0,04".

For more info check comments at [https://github.com/BCCN-Prog/webscraping_2018/commit/9d397bffc307ccb40d69f09ff3a4b36c79a33785](url)

**Comment by danvardan15** [comment]
see commit b27d7b4c5894d090d90a503a426215e03bc33cd0

**Comment by NHeere** [comment]
please see commit [1f871db](https://github.com/BCCN-Prog/webscraping_2018/commit/1f871dbd12ce071a376f51494e8a4f20c4936b23)

**Comment by mayarali** [comment]
Bug fixed.
